# Generated by Django 5.0.9 on 2025-07-16 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='borrow',
            unique_together=set(),
        ),
    ]
